[MS] Overhaul how clang passes vectors on x86_32
DONOTSUBMIT: Need to handle overaligned aggregate case.

Previously, on Windows, vector types would fall through to the end of
clang's argument classification and get passed directly. This is not
compatible with what MSVC does.

All tested MSVC versions pass up to three vectors directly in the
corresponding vector register, so XMM0-2, YMM0-2, and ZMM0-2. In MSVC
2013 and earlier, the compiler emits an error when a passing such a
vector by value:
  t.cpp(11) : error C2719: 'w': formal parameter with __declspec(align('32')) won't be aligned
  t.cpp(11) : error C2719: 'q': formal parameter with __declspec(align('32')) won't be aligned

This ABI lowering code seems like it dates to 2014, so at that point,
the decision of what to do for these arguments was arbitrary, since
there was nothing to be compatible with.

In MSVC 2015, such arguments are passed indirectly to ensure they are
aligned. This change implements that.

Related to this, when inalloca got involved, Clang would end up passing
vectors in the unaligned inalloca pack, instead of passing them in
vector registers. The first three values in registers need to be passed
out of order as we do for __fastcall and __vectorcall. The remainder
need to be passed with another level of indirection, which this change
implements.

Related to D71915

Fixes PR44395